title: ikovylyaev
email: hi@ikovylyaev.com
behance: ikovylyaev
telegram: ikovylyaev
dprofile: ikovylyaev
figma: ikovylyaev
description: >- 
  Дизайн-лид Xieffect.ru и веб-дизайнер в Код Екатеринбурга. Делаю удобные интерфейсы для людей.
  
baseurl: ""
url: "https://new.ikovylyaev.com"

theme:
  - custom

plugins:
  - jekyll-feed

collections:
  project:
    output: true
    sort_by: id
  work:
    output: true
    sort_by: id
